# Generated by Django 3.2.9 on 2021-12-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='food_pic',
            field=models.ImageField(blank=True, null=True, upload_to='recipe/'),
        ),
    ]
